import {layout, guideLayout, badge, arrow, sectionHeading, topicCard} from './components.mjs';
const topics = [
  {number:'01 / EXPLORE', title:'Know the way.', description:'Dungeon routes, maps, and the details that make your next run smoother.'},
  {number:'02 / PREPARE', title:'Bring what matters.', description:'Item requirements and preparation, gathered where you need them.'},
  {number:'03 / TEAM UP', title:'Find your rhythm.', description:'Party roles and encounter strategies to help your group work together.'}
];
export const home = () => layout({title:'The Forge', description:'Your next adventure starts here. A growing home for clear, practical MMORPG guides, beginning with Aion 2.', current:'home', content:`
<section class="hero container"><div class="hero-copy"><p class="eyebrow"><span class="tiny-star">✦</span> LESS SEARCHING. MORE ADVENTURING.</p><h1>Your next adventure.<br><em>Forged here.</em></h1><p class="lead">A home for the guides you wish you had.<br class="desktop-break"> Clear paths, better preparation, and everything<br class="desktop-break"> you need for the journey ahead.</p><div class="hero-actions"><a class="button" href="#games">Explore the games <span aria-hidden="true">↓</span></a><span class="subtle">Made for MMORPG adventurers</span></div></div><div class="forge-art" role="img" aria-label="A golden sun glowing above a dark steel anvil, the Solar Forge"><div class="orbit orbit-one"></div><div class="orbit orbit-two"></div><div class="orbit orbit-three"></div><div class="sun"></div><span class="art-star star-one">✦</span><span class="art-star star-two">✧</span><span class="art-star star-three">+</span><img class="solar-anvil" src="/assets/solar-anvil.svg" width="440" height="240" alt=""><div class="art-caption"><span>THE JOURNEY STARTS WITH A SPARK</span><span>✦</span></div></div></section>
<div class="principle-strip"><div class="container"><span>BUILT FOR THE WAY YOU PLAY</span><span>Thoughtful guides</span><span class="strip-star">✦</span><span>Useful details</span><span class="strip-star">✦</span><span>One place to begin</span></div></div>
<section id="games" class="container section">${sectionHeading('CHOOSE YOUR WORLD', 'Every adventure needs a starting point.', 'The library begins here. More worlds will follow.')}<a class="game-card" href="/games/aion-2/"><div class="game-art" aria-hidden="true"><span class="game-art-orbit"></span><span class="aion-wordmark">AION<span>2</span></span><span class="art-subtitle">A NEW WORLD AWAITS</span><div class="spire spire-one"></div><div class="spire spire-two"></div></div><div class="game-info"><div class="game-card-top"><span class="eyebrow">OUR FIRST WORLD</span>${badge('In the forge')}</div><h3>Aion 2</h3><p>A new adventure deserves a clearer path. We're building a home for your Aion 2 journey, one guide at a time.</p><div class="tags"><span>MMORPG</span><span>Dungeons</span><span>Party play</span></div><span class="text-link">Visit the Aion 2 hub ${arrow}</span></div></a><p class="library-note"><span aria-hidden="true">＋</span> A growing library, built with intention. More games on the horizon.</p></section>
<section id="about" class="about-section"><div class="container section">${sectionHeading('A LITTLE LESS GUESSWORK', 'Spend your time in the game.', 'Good preparation should be simple. That’s what we’re here to build.')}<div class="topic-grid">${topics.map(topicCard).join('')}</div></div></section>
<section class="container forge-note"><img class="note-mark" src="/assets/favicon.svg" width="45" height="45" alt=""><div><p class="eyebrow">THE FORGE IS JUST GETTING STARTED</p><h2>Small beginnings. A world of possibilities.</h2><p>We're starting with Aion 2 and building carefully from there.<br>Useful information, thoughtfully organized. That's the promise.</p></div><a class="text-link" href="/games/aion-2/">See what's taking shape ${arrow}</a></section>`});
export const aion = () => layout({title:'Aion 2', description:'The Aion 2 guide hub is taking shape. Explore our planned coverage for dungeons, items, and party preparation.', content:`<div class="container game-page"><nav class="breadcrumbs" aria-label="Breadcrumb"><a href="/">The Forge</a><span>/</span><a href="/#games">Games</a><span>/</span><span aria-current="page">Aion 2</span></nav><section class="game-hero"><div><p class="eyebrow">YOUR NEXT WORLD</p><h1>Aion <em>2</em></h1><p class="lead">A new world.<br>A better place to prepare.</p><p class="game-intro">Your future home for Aion 2 guides, dungeon preparation, and the details that bring a party together.</p>${badge('Guides coming soon')}</div><div class="portal" aria-hidden="true"><span>II</span></div></section><section class="section planning-section">${sectionHeading('CURRENTLY IN THE FORGE', 'The foundation of a better adventure.', 'No guides published yet. Here’s where we plan to begin.')}<div class="topic-grid">${topics.map(topicCard).join('')}</div></section><section class="status-panel"><span class="note-mark" aria-hidden="true">✦</span><div><h2>Good guides take a little crafting.</h2><p>We're laying the groundwork. Check back as the Aion 2 library takes shape.</p></div><a class="button button-secondary" href="/">Return to the Forge ${arrow}</a></section></div>`});
export const preview = () => guideLayout({title:'A clear title for your next guide', description:'A short summary explaining who this guide helps and what they will learn.', game:'Aion 2', gameHref:'/games/aion-2/', category:'Guide category', updated:'Preview only · Add a verified game version and review date when publishing.', sections:[{id:'overview',title:'Overview'},{id:'preparation',title:'Before you begin'},{id:'walkthrough',title:'Step by step'},{id:'references',title:'Sources & updates'}], notes:'<strong>Layout example, not game advice.</strong> Replace all example content with verified information before publishing.', content:`<section id="overview"><h2>Overview</h2><p>Start with the answer. Explain the goal and any important limitations in a few clear sentences.</p></section><section id="preparation"><h2>Before you begin</h2><ul><li>List verified entry requirements.</li><li>Explain items, roles, or preparation needed.</li><li>Identify the game region and patch this guide covers.</li></ul><div class="table-scroll" role="region" aria-label="Example requirements table" tabindex="0"><table><caption>Example table structure</caption><thead><tr><th scope="col">Requirement</th><th scope="col">Details</th><th scope="col">Where to verify</th></tr></thead><tbody><tr><td>Entry item</td><td>Verified quantity goes here</td><td>Source link goes here</td></tr></tbody></table></div></section><section id="walkthrough"><h2>Step by step</h2><ol><li>Describe the first action and its purpose.</li><li>Explain the next decision with a clear outcome.</li><li>Summarize the reward or next destination.</li></ol><details><summary>Optional details and common questions</summary><p>Use native disclosure for supporting details. Keep critical instructions visible.</p></details></section><section id="references"><h2>Sources & updates</h2><p>Link primary sources, describe verification, and record substantive changes. Do not present guesses as confirmed mechanics.</p></section>`});
export const notFound = () => layout({title:'Page not found', description:'Find your way back to Solar Forge Game Guides.', noindex:true, content:'<section class="container empty-page"><p class="eyebrow">404 · A PATH YET TO BE FORGED</p><h1>A little off the map.</h1><p class="lead">This page could not be found. Your next adventure is still waiting.</p><a class="button" href="/">Return to the Forge ↗</a></section>'});
